import type { EncounterDefinition } from './types';

const registrationFlags = {
  gundulaConvinced: true,
  checkoutHeadcountPending: true,
  checkoutTentPending: true,
  powerUnregistered: true,
  checkoutSurchargePending: true,
};

export const ARRIVAL_ENCOUNTERS: Record<string, EncounterDefinition> = {
  'gundula-entry': {
    id: 'gundula-entry',
    speaker: 'Gundula',
    portrait: 'G',
    intro: 'Gundula findet die Reservierung tatsächlich. „Tauchgruppe Tiefenrausch. Drei Personen, zwei Zelte, kein Strom. Vor mir stehen mehr Taschen als Angaben. Erkläre.“',
    options: [
      {
        id: 'manifest',
        label: 'Die Buchung exakt auswendig aufsagen',
        hint: 'Fokus · der richtige falsche Name und die geschönten Zahlen',
        challenge: { skill: 'focus', baseChance: 72, relation: 'gundula' },
        successText: 'Gundula akzeptiert die Buchung vorläufig und markiert Personen, Zelte und Strom für die Endabrechnung.',
        failureText: 'Du vertauschst Zeltzahl und Personenzahl. Gundula beginnt ein neues Blatt nur für euch.',
        greatText: 'Du nennst Alias, Taucherplatz und Buchungsumfang ohne Luft zu holen. Gundula ist gegen ihren Willen beeindruckt.',
        disasterText: 'Du verwendest ausgerechnet den Reservierungsnamen vom letzten Jahr. Gundula legt beide Akten nebeneinander.',
        success: {
          flags: registrationFlags,
          relationships: { gundula: 12 },
          metrics: { dignity: 3, reputation: 2, momentum: 5, chaos: 1 },
          minutes: 7,
        },
        failure: {
          relationships: { gundula: -6 },
          metrics: { dignity: -4, chaos: 3, momentum: -4 },
          minutes: 6,
        },
      },
      {
        id: 'compact-group',
        label: '„Wir sind eine sehr kompakte Tauchgruppe.“',
        hint: 'Charme · neun Leute sprachlich auf drei verdichten',
        challenge: { skill: 'charm', baseChance: 57, relation: 'gundula' },
        successText: 'Gundula lässt die Formulierung aus Erschöpfung gelten. Bezahlt wird bei Abreise.',
        failureText: 'Gundula zählt sichtbare Campingstühle. Die Zahl liegt bereits über der Anmeldung.',
        success: {
          flags: registrationFlags,
          relationships: { gundula: 8 },
          metrics: { dignity: 2, chaos: 3, momentum: 4 },
          minutes: 6,
        },
        failure: {
          relationships: { gundula: -7 },
          metrics: { dignity: -5, chaos: 4, momentum: -5 },
          minutes: 6,
        },
      },
      {
        id: 'batida-paperweight',
        label: 'Batida de Coco als Aktenbeschwerer anbieten',
        hint: 'Teamwork · benötigt Batida, die Flasche bleibt vorerst geschlossen',
        requiredItem: 'batida',
        challenge: { skill: 'teamwork', baseChance: 88, relation: 'gundula' },
        successText: 'Die Kokosdiplomatie wirkt. Gundula stempelt den Zettel und verschiebt alle Widersprüche auf Sonntag.',
        failureText: 'Gundula lehnt Bestechung ab, dreht die Flasche aber so, dass sie das Etikett lesen kann.',
        success: {
          flags: { ...registrationFlags, batidaRegulatedRegistration: true },
          relationships: { gundula: 16 },
          metrics: { reputation: 2, chaos: 2, momentum: 7 },
          minutes: 4,
        },
        failure: {
          relationships: { gundula: -5 },
          metrics: { dignity: -3, chaos: 3, momentum: -3 },
          minutes: 4,
        },
      },
    ],
  },
  'uli-entry': {
    id: 'uli-entry',
    speaker: 'Uli',
    portrait: 'U',
    intro: 'Uli mustert Fahrzeug, Taucherplatz-Zettel und dein Oberteil. „Lidl und Aldimania machen also jetzt auch Mode. Manche feiern das als Hype. Andere fragen, warum man Klamotten beim Discounter kauft, ob man sich nichts Vernünftiges leisten kann oder gleich dort arbeitet. Welche Erklärung soll ich eintragen?“',
    options: [
      {
        id: 'cover-logo',
        label: 'Funktion vor Preis erklären und den Lageplan zeigen',
        hint: 'Fokus · günstige Kleidung ist nicht automatisch schlechte Kleidung',
        challenge: { skill: 'focus', baseChance: 76, relation: 'uli' },
        successText: 'Du erklärst Material, Funktion und Preis ohne Markenpredigt. Uli akzeptiert, dass kostenbewusst nicht dasselbe wie mittellos bedeutet, und prüft wieder den Taucherplatz.',
        failureText: 'Die Erklärung klingt wie eine Rechtfertigung. Uli fragt trocken, ob es zum Outfit auch Mitarbeiterrabatt gab.',
        greatText: 'Du trennst Preis, Qualität und Markenimage so sauber wie Uli seine Parzellengrenzen. Er findet keinen sachlichen Einwand.',
        success: {
          flags: { uliInspectionPassed: true },
          relationships: { uli: 12 },
          metrics: { dignity: 4, momentum: 5 },
          minutes: 5,
        },
        failure: {
          relationships: { uli: -5 },
          metrics: { dignity: -4, chaos: 2, momentum: -3 },
          minutes: 5,
        },
      },
      {
        id: 'aldimania-fashion',
        label: 'Die Discounter-Kollektion als aktuellen Hype verteidigen',
        hint: 'Charme · für manche Kultstück, für andere billige Mode',
        challenge: { skill: 'charm', baseChance: 48, relation: 'uli' },
        successText: 'Du verkaufst Lidl und Aldimania als bewusst ironische, limitierte Alltagsmode. Uli hat den Hype nicht verfolgt und will seine Wissenslücke nicht protokollieren.',
        failureText: 'Uli besitzt ein ähnliches Oberteil zum Rasenmähen und hält den angeblichen Hype für eine nachträgliche Schutzbehauptung.',
        success: {
          flags: { uliInspectionPassed: true, aldimaniaAcceptedAsFashion: true },
          relationships: { uli: 6 },
          metrics: { chaos: 3, reputation: 2, momentum: 4 },
          minutes: 5,
        },
        failure: {
          relationships: { uli: -8 },
          metrics: { dignity: -5, chaos: 4, momentum: -5 },
          minutes: 5,
        },
      },
      {
        id: 'batida-vest',
        label: 'Batida-Flasche als Warnsignal präsentieren',
        hint: 'Chaos · benötigt Batida, erstaunlich etablierte Methode',
        requiredItem: 'batida',
        challenge: { skill: 'chaos', baseChance: 80, relation: 'uli' },
        successText: 'Uli erkennt das bekannte Kokos-Protokoll und erklärt die Kleidungsdebatte für zweitrangig.',
        failureText: 'Die Flasche reflektiert nichts und erfüllt keine einzige Warnwestennorm.',
        success: {
          flags: { uliInspectionPassed: true, batidaRegulatedOutfit: true },
          relationships: { uli: 9 },
          metrics: { chaos: 4, momentum: 6 },
          minutes: 4,
        },
        failure: {
          relationships: { uli: -5 },
          metrics: { dignity: -4, chaos: 4, momentum: -4 },
          minutes: 4,
        },
      },
    ],
  },
  'power-box': {
    id: 'power-box',
    speaker: 'Stromkasten T-7',
    portrait: '⚡',
    intro: 'Der Taucherplatz ist eingetragen, der Stromanschluss nicht. Drei Dosen sind frei, zwei davon gehören nachweislich jemand anderem.',
    options: [
      {
        id: 'socket-t7',
        label: 'Plan lesen und Anschluss T-7 verwenden',
        hint: 'Fokus · richtige Dose, falsche Anmeldung',
        challenge: { skill: 'focus', baseChance: 74 },
        successText: 'Anschluss T-7 ist identifiziert. Technisch korrekt, verwaltungstechnisch unsichtbar – jetzt fehlt nur noch eure Kabeltrommel.',
        failureText: 'Du erwischst den Kühlschrankanschluss der Dauercamper. Innerhalb von Sekunden steht jemand im Bademantel da.',
        success: {
          flags: { powerAccessOrganized: true, checkoutPowerPending: true, powerUsedWithoutBooking: true },
          metrics: { chaos: 2, momentum: 5 },
          minutes: 8,
        },
        failure: {
          metrics: { dignity: -3, chaos: 4, momentum: -3 },
          minutes: 6,
        },
      },
      {
        id: 'batida-splitter',
        label: 'Batida gegen ein Schuko-T-Stück tauschen',
        hint: 'Teamwork · benötigt und verbraucht eine Batida-Flasche',
        requiredItem: 'batida',
        consumeItemOnSuccess: 'batida',
        challenge: { skill: 'teamwork', baseChance: 94 },
        successText: 'Ein Nachbar liefert Adapter, Anschlusswissen und keine Fragen. Batida de Coco regelt erneut; die Kabeltrommel müsst ihr noch ausladen.',
        failureText: 'Der Nachbar trinkt grundsätzlich nur Eierlikör. Die Verhandlung scheitert kulturell.',
        success: {
          flags: { powerAccessOrganized: true, checkoutPowerPending: true, batidaRegulatedPower: true },
          metrics: { reputation: 2, chaos: 3, momentum: 8 },
          minutes: 5,
        },
        failure: {
          metrics: { dignity: -2, chaos: 2, momentum: -2 },
          minutes: 4,
        },
      },
      {
        id: 'late-registration',
        label: 'Uli eine verspätete Stromanmeldung abringen',
        hint: 'Nerven · sauberer, aber deutlich anstrengender',
        challenge: { skill: 'nerve', baseChance: 52, relation: 'uli' },
        successText: 'Uli weist euch Anschluss T-7 zu und unterstreicht dreimal, dass die Gebühr bei Abreise fällig wird. Jetzt fehlt die Kabeltrommel.',
        failureText: 'Uli verlangt das Formular aus der Rezeption. Gundula verlangt dafür Uli. Der Kreis ist geschlossen.',
        success: {
          flags: { powerAccessOrganized: true, checkoutPowerPending: true, powerRegisteredLate: true },
          relationships: { uli: 4 },
          metrics: { dignity: 3, momentum: 3 },
          minutes: 12,
        },
        failure: {
          relationships: { uli: -3 },
          metrics: { dignity: -2, momentum: -4 },
          minutes: 9,
        },
      },
    ],
  },
};
